name: Compile and upload résumé PDF
on:
  push:
    branches:
      - "master"
    paths:
      - "resume.tex"
      - ".github/workflows/**"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - uses: EndBug/add-and-commit@v9
        with:
          add: resume.pdf
